<div class="container_16">
    <div class="grid_16">
        <p class="foot_note">
            <a href="https://github.com/simukti/UrlNote">UrlNote</a> Powered by <a href="http://framework.zend.com/">ZF v<?php echo \Zend_Version::VERSION ?></a> - Copyright &copy; <?php $year = date('Y'); echo $year == '2012' ? $year : sprintf("2012-%s", $year); ?> - <a href="http://simukti.net">Sarjono Mukti Aji</a>
        </p>
    </div>
</div>