<?php if ($this->pageCount): ?>
<div class="pagination">
    <ul>
        <?php if (isset($this->previous)): ?>
            <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&larr; Previous</a></li>
        <?php else: ?>
            <li class="unavailable"><a href="#">&larr; Previous</a></li>
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page === $this->current): ?>
                <li class="current"><a href="#"><?php echo $page; ?></a></li>
            <?php else: ?>
                <li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
            <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">Next &rarr;</a></li>
        <?php else: ?>
            <li class="unavailable"><a href="#">Next &rarr;</a></li>
        <?php endif; ?>
    </ul>
</div>
<?php endif; ?>